dma/urls.py
from django.conf.urls import url

from django.views.generic import TemplateView

from .views import (
    DmazoneListview,
    
    WbalanceListview,
    EconomyListview,
    StaticListview,
    press_value,
    MeasureCreateView,
    MeasureUpdateView,
)

app_name = 'dma'
urlpatterns = [
    #url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', DmazoneListview.as_view(), name='detail'),
    url(r'^$', DmazoneListview.as_view()),
    # url(r'^(?P<slug>[\w-]+)/wbalance/$', TemplateView.as_view(template_name='dma/wbalance.html'),name='wbalance'),
    url(r'^(?P<slug>[\w-]+)/wbalance/$', WbalanceListview.as_view()),
    url(r'^(?P<slug>[\w-]+)/economy/$', EconomyListview.as_view()),
    url(r'^(?P<slug>[\w-]+)/static/$', StaticListview.as_view()),

    #dma create update etc
    url(r'^(?P<slug>[\w-]+)/create/$', MeasureCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$', MeasureUpdateView.as_view(), name='edit'),

    url(r'^press_value', press_value, name='press_value'),
    
]

virvo/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

from . import views

app_name = 'virvo'
urlpatterns = [
    
    url(r'^$', TemplateView.as_view(template_name='virvo/test_home.html'),name='virvo_home'),

    url(r'editform/$', TemplateView.as_view(template_name='virvo/edit_form.html'),name='editform'),
    url(r'getstationtree/$',views.get_stationtree,name='getstationtree'),
    url(r'getdmatree/$',views.get_dmatree,name='getdmatree'),

    url(r'gettree/$',views.gettree,name='gettree'),
    url(r'getchartd/$',views.getchartd,name='getchartd'),

    url(r'createdma/$',views.create_dma,name='create_dma'),
    url(r'dma/(?P<pk>\d+)/$', views.DMAListView.as_view(),name='dma_manager'),

    url(r'^dma/(?P<dma_id>\d+)/daily/$', views.DailyuseView.as_view(), name="daily_use"),
    
    url(r'mnf/$', views.MNFView.as_view(),name='mnf'),
    url(r'^dma/(?P<dma_id>\d+)/mapmonitor/?$', TemplateView.as_view(template_name='virvo/map_monitor.html'),name='map_monitor'),

    url(r'^dma/(?P<dma_id>\d+)/rt_curve/$', views.rt_curveView.as_view(), name="rt_curve"),
    url(r'^dma/(?P<dma_id>\d+)/rt_data/$', views.rt_dataView.as_view(), name="rt_data"),
    url(r'^station/alarms/(?P<pk>[0-9]+)/?$', views.StationsAlarmView.as_view(), name='stations_alarms_message'),

    # 
    url(r'^station/create/?$', views.StationsCreateMangerView.as_view(), name='stations_create_manager'),
    url(r'^dma/(?P<dma_id>\d+)/station/?$', views.StationsListMangerView.as_view(), name='stations_list_manager'),
    url(r'^station/update/(?P<pk>[0-9]+)/?$', views.StationsUpdateManagerView.as_view(), name='stations_edit_manager'),
    
]

virvo/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.dateparse import parse_datetime
from django.contrib.admin import widgets
from django.contrib.admin.widgets import AdminDateWidget,AdminSplitDateTime
from django.contrib.postgres.forms.ranges import DateRangeField, RangeWidget

# from crispy_forms.helper import FormHelper
# from crispy_forms.layout import Layout

from . import models
from .models import Stations
import datetime
# import settings

class CreateDMAForm(forms.Form):

    dma_no      = forms.CharField(label='分区编号',max_length=20)
    dma_name    = forms.CharField(label='分区名称',max_length=20)
    creator     = forms.CharField(label='负责人',max_length=20)
    create_date  = forms.DateField(label='建立日期')

    

# date_available = forms.DateField(
        # widget=forms.widgets.DateInput(format="%m/%d/%Y"))




class DMABaseinfoForm(forms.ModelForm):

    orgs = forms.ModelChoiceField(label='所属组织',queryset=models.Organization.objects.all())

    class Meta:
        model = models.DMABaseinfo
        fields = [
            'dma_no',  
            'pepoles_num',
            'acreage',    
            'user_num',    
            'pipe_texture',         
            'pipe_length',       
            'pipe_links',      
            'pipe_years',   
            'pipe_private',      
            'ifc',   
            'aznp',   
            'night_use',      
            'cxc_value',     
        ]

    def __init__(self, *args, **kwargs):
        super(DMABaseinfoForm, self).__init__(*args, **kwargs)
        if self.instance.dma.parent:
            self.fields['orgs'].initial = self.instance.dma.parent.pk
        else:
            self.fields['orgs'].initial =  1


class TestForm(forms.ModelForm):

    class Meta:
        model = models.Stations
        fields = [
            'station_name',  
            'meter_property',
            'meter_type',    
            'meter_code',    
            'simno',         
            'caliber',       
            'big_user',      
            'focus',         
            # 'installed',     
        ]

    # @property
    # def helper(self):
    #     helper = FormHelper()
    #     helper.form_tag = False # don't render form DOM element
    #     helper.render_unmentioned_fields = True # render all fields
    #     helper.label_class = 'col-md-2'
    #     helper.field_class = 'col-md-10'
    #     return helper        


"""
Stations creation, manager
"""
class StationsCreateManagerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(StationsCreateManagerForm, self).__init__(*args, **kwargs)
        # self.fields['invoice_date'].widget.attrs['class'] = 'calendar'
    class Meta:
        model = Stations
        fields= '__all__'

"""
Stations edit, manager
"""
class StationsForm(forms.ModelForm):


    def __init__(self, *args, **kwargs):
        super(StationsForm, self).__init__(*args, **kwargs)
        # self.fields['invoice_date'].widget.attrs['class'] = 'calendar'
        self.fields['belongto']=forms.ModelChoiceField(queryset=models.Organization.objects.all())
        qs = models.Stations.objects.all()
        qs1 = qs.order_by('meter_property').values_list('meter_property', flat=True)
        # self.fields['meter_property']=forms.ModelChoiceField(queryset=qs1.distinct())
        self.fields['meter_property'].choices=enumerate(['工业用水','商业用水','特种行业用水','行政事业用水','绿化用水'])
        self.fields['installed'].widget = forms.widgets.DateInput(format="%d-%m-%Y")
        

    class Meta:
        model = Stations    
        fields= '__all__'

virvo/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404,render
from django.http import HttpResponse,JsonResponse,HttpResponseRedirect
from django.contrib import messages
from . models import Organization,Stations,DMABaseinfo,Alarms
import json
import random
from datetime import datetime

from mptt.utils import get_cached_trees
from mptt.templatetags.mptt_tags import cache_tree_children

from django.template.loader import render_to_string
from django.shortcuts import render,HttpResponse
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView,FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .tables import StationsTable
from django_tables2 import RequestConfig

from django.urls import reverse_lazy
from .forms import DMABaseinfoForm,CreateDMAForm,TestForm,StationsCreateManagerForm,StationsForm

import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import FormView, TemplateView
# from django.core.urlresolvers import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin




# from dma.fusioncharts import FusionCharts


# from .fusioncharts import FusionCharts

# Create your views here.


def recursive_node_to_dict(node,url_cat):
    result = {
        'id':node.pk,
        'name': node.name,
        'open':'true',
        'url':'/virvo/dma/{}/{}'.format(node.pk,url_cat),
        'target':'_self',
        'icon':"/static/virvo/images/站点管理/u842_1.png",
    }
    
    children = [recursive_node_to_dict(c,url_cat) for c in node.get_children()]
    
    # get each node's station if exist
    # try:
    #     sats = node.station.all()
    #     for s in sats:
    #         children.append({'name':s.station_name})
    #     # children.append({'name':})
    # except:
    #     pass

    if children:
        result['children'] = children
    
    return result

def get_stationtree(request):
    organs = Organization.objects.all()
    
    top_nodes = get_cached_trees(organs)

    dicts = []
    for n in top_nodes:
        dicts.append(recursive_node_to_dict(n,'station'))

    
    # print json.dumps(dicts, indent=4)

    
    
    return JsonResponse({'trees':dicts})


def get_dmatree(request):
    organs = Organization.objects.all()
    
    top_nodes = get_cached_trees(organs)

    dicts = []
    for n in top_nodes:
        dicts.append(recursive_node_to_dict(n,''))

    
    # print json.dumps(dicts, indent=4)

    
    
    return JsonResponse({'trees':dicts})

def gettree(request):
    print(request.GET)
    page_name = request.GET.get('page_name') or ''
    print(page_name)
    organs = Organization.objects.all()
    
    top_nodes = get_cached_trees(organs)

    dicts = []
    for n in top_nodes:
        dicts.append(recursive_node_to_dict(n,page_name))

    
    # print json.dumps(dicts, indent=4)

    
    
    return JsonResponse({'trees':dicts})

def gettreenode(request):
    node = request.POST['node']
    
    orgs = Organization.objects.filter(name=node).first()
    
    table = StationsTable(Stations.objects.filter(belongto=orgs))
    
    # table = StationsTable(orgs.station_set.all())
    
    RequestConfig(request, paginate={'per_page': 10}).configure(table)
    
    vals = {'table':table}
    return render(request,'virvo/table_station.html',vals)
    # return JsonResponse(vals)    

def getchartd(request):
    data = [random.randint(2,13), 20, 6, 10, 20, 30]

    return JsonResponse({'data':data})  

class rt_curveView(TemplateView):
    """docstring for rt_curveView"""
    template_name = 'virvo/rt_curve.html'

    def get_context_data(self, *args, **kwargs):
        context = super(rt_curveView, self).get_context_data(*args, **kwargs)
        context['page_title'] = '实时曲线'
        dma_id = self.kwargs.get('dma_id') or 1
        orgs = Organization.objects.get(pk=dma_id)
        stations_list = Stations.objects.filter(belongto=orgs)
        context['station_list'] = stations_list

        for station in stations_list:
            pass

        rt_dataset = []
        def curse_data(s):
            result = {
                'chart_id':'chart_{}'.format(s.station_name),
                'data':[1,2,3,4,5,6],
                'station_name':s.station_name,
                'caliber':s.caliber
            }
            return result

        jsd=[]
        for s in stations_list:
            rt_dataset.append(curse_data(s) )
            jsd.append({'data':[random.randint(2,13), random.randint(2,13), random.randint(2,13), random.randint(2,13), random.randint(2,13), random.randint(2,13)],
                'name':'chart_{}'.format(s.station_name)})
        
        context['rt_dataset'] = rt_dataset
        dum=json.dumps(jsd)
        # print(type(dum),dum)

        data = [random.randint(2,13), 20, 6, 10, 20, 30]
        context['jsd'] = json.dumps(jsd)

        

        return context
        

class rt_dataView(TemplateView):
    """docstring for rt_curveView"""
    template_name = 'virvo/rt_data.html'

    def get_context_data(self, *args, **kwargs):
        context = super(rt_dataView, self).get_context_data(*args, **kwargs)
        context['page_title'] = '实时数据'
        dma_id = self.kwargs.get('dma_id') or 1
        orgs = Organization.objects.get(pk=dma_id)
        stations_list = Stations.objects.filter(belongto=orgs)
        context['stations_list'] = stations_list

        

        return context

class MNFView(TemplateView):
    """docstring for StationsView"""

    
    template_name = 'virvo/mnf.html'
    
    def get_context_data(self, *args, **kwargs):
        
        context = super(MNFView, self).get_context_data(*args, **kwargs)

        
        # if self.request.method == 'POST':
        #     form = AnalyWaterForm(self.request.POST or None)
        # else:
            
        #     form = AnalyWaterForm()
            
        # context['form'] = form

        # table = StationsTable(Stations.objects.all())
        # RequestConfig(self.request, paginate={'per_page': 10}).configure(table)
        # context['table'] = table

        
                
        return context                 


class AjaxTemplateMixin(object):
    
    def dispatch(self, request, *args, **kwargs):
        if not hasattr(self, 'ajax_template_name'):
            split = self.template_name.split('.html')
            split[-1] = '_inner'
            split.append('.html')
            self.ajax_template_name = ''.join(split)
        if request.is_ajax():
            self.template_name = self.ajax_template_name
        return super(AjaxTemplateMixin, self).dispatch(request, *args, **kwargs)


class TestFormView(SuccessMessageMixin, AjaxTemplateMixin, FormView):
    template_name = 'virvo/test_form.html'
    form_class = TestForm
    success_url = reverse_lazy('home')
    success_message = "Way to go!"        



def create_dma(request):
    
    print(request.POST)
    if request.method == 'POST':
        # dma_no = request.POST.get('dma_no')
        # dma_name = request.POST.get('dma_name')
        # creator = request.POST.get('creator')
        create_date = request.POST.get('create_date')
        print(create_date)
    dma_form = CreateDMAForm(request.POST or None)
    if dma_form.is_valid():
        parent = Organization.objects.first()
        orgs = Organization.objects.create(name=dma_form.cleaned_data.get('dma_name'),parent=parent)

        obj = DMABaseinfo.objects.create(dma_no=dma_form.cleaned_data.get('dma_no'),dma=orgs)
        # return HttpResponseRedirect("/virvo/dma/1/")
    if dma_form.errors:
        print(dma_form.errors)
    return render(request,'virvo/dma_manager.html',{'dma_form':dma_form})

class DMAListView(UpdateView):
    template_name = 'virvo/dma_manager.html'
    form_class = DMABaseinfoForm
    model = DMABaseinfo
    # success_url = '/virvo/dma/1'

    def get_queryset(self):
        return DMABaseinfo.objects.all()

    def get_form_kwargs(self):
        print (self.kwargs)
        kwargs = super(DMAListView, self).get_form_kwargs()
        # kwargs['user'] = self.request.user
        print (kwargs)
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context = super(DMAListView, self).get_context_data(*args, **kwargs)
        context['title'] = 'DMA 管理'
        pk = self.kwargs.get('pk')
        orgs = Organization.objects.get(pk=pk)
        context['station_list'] = Stations.objects.filter(belongto=orgs)

        create_dma_form = CreateDMAForm()
        context['dma_form'] = create_dma_form

        return context

    def form_valid(self,form):
        orgs = form.cleaned_data.get('orgs')
        print(orgs,type(orgs))
        print (form.instance)
        print(form.instance.dma)
        # print(form.instance.dma.parent)
        form.instance.dma.parent = orgs
        form.instance.dma.save()

        return super(DMAListView,self).form_valid(form)





"""
Stations creation, manager
"""
class StationsCreateMangerView(CreateView):
    model = Stations
    template_name = 'virvo/stations_create_manager.html'
    form_class = StationsCreateManagerForm
    # success_url = reverse_lazy('stations_list_manager');

    # @method_decorator(permission_required('virvo.change_stations'))
    def dispatch(self, *args, **kwargs):
        return super(StationsCreateMangerView, self).dispatch(*args, **kwargs)


"""
Stationss list, manager
"""
class StationsListMangerView(ListView):
    model = Stations
    template_name = 'virvo/stations_list_manager.html'

    # @method_decorator(permission_required('virvo.change_stations'))
    def dispatch(self, *args, **kwargs):
        return super(StationsListMangerView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        # user = self.request.user
        # manager_group = Group.objects.get(name=settings.BANCOAUSILI_MANAGER_GROUP)

virvo/templates/virvo/alarminfo.html
<div class="modal-dialog " >
    <div class="modal-content">


      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="exampleModalLabel">报警信息</h4>
      </div>
      <div class="modal-body">
        <table class="table table-bordered">
            <thead>
              <tr>
                
                <th >报警类型</th>
                <th>报警时间</th>
                
                
              </tr>

            </thead>
            <tbody>
                {% for q in qs %}
                    <tr>
                        <td>{{ q.alarm_type }}</td>
                        <td>{{ q.report_time }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
            
            
      </div>
             
        

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->


virvo/templates/virvo/daily_use.html
{% extends 'virvo/_base.html' %}




{% block organizationtree %}
<div class=" treel">
  {% include 'virvo/stationtree.html' %}
</div>
{% endblock %}


{% block content %}
<div class=" context">
    

<div  class="ax_default">

  <div class="list-group" role="tab" id="heading">
      <div>
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1" class="list-group-item active main-color-bg">
          <span class="fa fa-caret-down" title="Toggle dropdown menu"></span> 图形分析
        </a>
      </div>
      
          <div id="collapse1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading">
            <div>
              <form>
                <input type="text" name="sname">
                <input type="submit" name="btn_seach">
                
              </form>
              <button id="add_station"><a href="{% url 'virvo:stations_create_manager' %}" data-toggle="modal" data-target="#modal" class="fa fa-pencil" title="create stations" data-tooltip>新增</a></button>
              
            </div>
        </div>


        <div >
        <div id="chart_station" style="width: 1200px;height:555px;"></div>
        
      </div>
      
  </div>



    


    
</div>
{% endblock %}


{% block javascript %}
{{ block.super }}
    

    <script>
        
        $(function(){
          load_Tree('daily');
        });


        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('chart_station'));
        var server_info;
        // 指定图表的配置项和数据
        var option = {
            // title: {
            //     text: 'ECharts 入门示例'
            // },
            tooltip: {},
            legend: {
                data:['昨日曲线','当日柱状图',]
            },
            
            xAxis: {
                data: ["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24"]
            },
            yAxis: {},
            series: [
              {
                  name: '当日柱状图',
                  type: 'bar',
                  data: [37, 28, 26, 26, 29, 30,40,48,54,58,62,58,55,54,52,48,52,54,56,58,62,63,64,58,48]
              },
              {
                  name: '昨日曲线',
                  type: 'line',
                  data: [37, 28, 26, 26, 29, 30,40,48,54,58,62,58,55,54,52,48,52,54,56,58,62,63,64,58,48]
              },
            ]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart.setOption(option);

        
 

        // myChart.setOption(option, true);

            
 
         window.onresize = function () {
            myChart.resize();      
        };

        
    </script>

{% endblock %}

virvo/templates/virvo/dmatree.html
{% load staticfiles %}



<!-- 组织列表面板 (动态面板) -->
<div class="tree_hd">
  <div class="col-md-10 " ><span class="center">组织架构</span></div>
  <div class="col-md-2">
    <a data-toggle="collapse" data-parent="#accordion" href="#collapse0" aria-expanded="true" aria-controls="collapse0" class="list-group-item active ">
          <span class="fa fa-angle-down" title="Toggle dropdown menu"></span>
    </a>
  </div>
</div>

<div id="collapse0" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="tree_heading" >
    <div>

    <!-- Unnamed (文本框) -->
    <div class="ax_default _输入框 center" style="margin-top: 20px;margin-left: 20px;">
      <input id="u837_input" type="text" value="请输入组织名称"/>
    </div>

    <!-- Unnamed (树状菜单) -->
      <div class="ax_default _组织架构 treeroot" style="cursor: default;">
        <ul id="dma_tree" class="ztree"></ul>
      </div>
    </div>
</div>





              



virvo/templates/virvo/stations_create_manager.html

<div class="modal-dialog " style="width: 1200px;">
    <div class="modal-content">

        <form id="create_stations" method='post' class="form" role="form" action='{% url 'virvo:stations_create_manager'  %}'>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                
              </div>
              <div class="modal-body">
                    
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.errors %}
                                <ul class="form-errors">
                                {% for error in field.errors %}
                                    <li><span class="fa fa-exclamation-triangle"></span> <strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                            {{ field.label_tag }} {{ field }} 
                            {% if field.help_text %}<div class="form-helptext">{{ field.help_text }}</div>{% endif %}
                        </div>
                    {% endfor %}
                    
              </div>
              <div class="modal-footer">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="close" />
                <input type="submit" class="btn btn-primary" value="submit" style="margin-bottom: 5px;" />
              </div>
        </form>

    <script>
        jQuery('.modal-content .calendar').datepicker({ dateFormat: "yy-mm-dd" });

        var form_options = {
            target: '#modal',
            success: function() { console.log('create success...'); }
        }
        $('#create_stations').ajaxForm(form_options);
    </script>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->


virvo/templates/virvo/stations_edit_manager.html
<div class="modal-dialog " style="width: 1200px;">
    <div class="modal-content">

        <form id="stations_update_form" method='post' class="form" role="form" action='{% url 'virvo:stations_edit_manager' object.id %}'>
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                
              </div>
              <div class="modal-body">
                    
                    {% csrf_token %}
                    {{ form.non_field_errors }}
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.errors %}
                                <ul class="form-errors">
                                {% for error in field.errors %}
                                    <li><span class="fa fa-exclamation-triangle"></span> <strong>{{ error|escape }}</strong></li>
                                {% endfor %}
                                </ul>
                            {% endif %}
                            {{ field.label_tag }} {{ field }} 
                            {% if field.help_text %}<div class="form-helptext">{{ field.help_text }}</div>{% endif %}
                        </div>
                    {% endfor %}
                    
              </div>
              <div class="modal-footer">
                <input type="button" class="btn btn-default" data-dismiss="modal" value="close" />
                <input type="submit" class="btn btn-primary" value="submit" style="margin-bottom: 5px;" />
              </div>
        </form>

    <script>
        // jQuery('.modal-content .calendar').datepicker({ dateFormat: "yy-mm-dd" });

        var form_options = {
            target: '#modal',
            success: function() {  }
        }
        $('#stations_update_form').ajaxForm(form_options);
    </script>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

virvo/templates/virvo/stations_edit_manager_success.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Cespite {{ stations.id }}</h4>
              </div>
              <div class="modal-body">
                  <p>Modifiche effettuate con successo</p>
                  <script>
                    setTimeout(function() { jQuery('#modal').modal('hide'); }, 1000);
                    $('body').on('hidden.bs.modal', '.modal', function () {
                        $(this).removeData('bs.modal');
                    });
                  </script>
              </div>
              <div class="modal-footer">
              </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->

virvo/templates/virvo/stations_list_manager.html
{% extends 'virvo/_base.html' %}


{% block javascript %}
{{ block.super }}
    <script src="http://malsup.github.com/jquery.form.js"></script>

{% endblock %}

{% block organizationtree %}
<div class=" treel">
  {% include 'virvo/stationtree.html' %}
</div>
{% endblock %}


{% block content %}
<div class=" context">
    <!-- Modal -->
    <!-- <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    </div> --><!-- /.modal -->
    <div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document" style="width: 1200px;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

<div  class="ax_default">

  <div class="list-group" role="tab" id="heading">
      <div>
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse1" aria-expanded="true" aria-controls="collapse1" class="list-group-item active main-color-bg">
          <span class="fa fa-caret-down" title="Toggle dropdown menu"></span> 站点管理
        </a>
      </div>
      
          <div id="collapse1" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading">
            <div>
              <form>
                <input type="text" name="sname">
                <input type="submit" name="btn_seach">
                
              </form>
              <button id="add_station"><a href="{% url 'virvo:stations_create_manager' %}" data-toggle="modal" data-target="#modal" class="fa fa-pencil" title="create stations" data-tooltip>新增</a></button>
              <table id="tb_stations" class="table table-bordered">
                <thead>
                  <tr>
                    
                    <th >序号</th>
                    <th>选择</th>
                    <th></th>
                    <th >站点名称</th>
                    <th >用水性质</th>
                    <th >表具类型</th>
                    <th >表具编号</th>
                    <th >SIM卡号</th>
                    <th >口径</th>
                    <th >所属组织</th>
                    <th >大用户</th>
                    <th >重点关注</th>
                    <th >安装日期</th>
                    
                  </tr>
  
                </thead>
               {% for stations in object_list %}
                  <tr>
                    <td>{{ obj.id }} </td>
                    <td><input type="checkbox"/> </td>
                    <td class="btn_del">
                      <div>
                        <button class="btn alter-button" ><a href="{% url 'virvo:stations_edit_manager' stations.id %}" data-toggle="modal" data-target="#modal" class="fa fa-pencil" title="update stations" data-tooltip>修改</a></button>
                        <button type = "button" class = "btnDelete">删除</button>
                         
                      </div>
                    </td>

                    
          
                    <td>{{ stations.station_name }} </td>
                    <td>{{ stations.meter_property }} </td>
                    <td>{{ stations.meter_type }} </td>
                    <td>{{ stations.meter_code }} </td>
                    <td>{{ stations.simno }} </td>
                    <td>{{ stations.caliber }} </td>
                    <td>{{ stations.belongto }} </td>
                    <td>{{ stations.big_user }} </td>
                    <td>{{ stations.focus }} </td>
                    <td>{{ stations.installed }} </td>
                    
                  </tr>
                  
               {% endfor %}
             </table>
            </div>
        </div>
      
  </div>



    


    <script>
        console.log('stations_list_manger...')

        $(function(){
          load_Tree('station');
        });

        $('body').on('hidden.bs.modal', '.modal', function () {
            console.log('hidden??...')
            $(this).removeData('bs.modal');
        });
    </script>
</div>
{% endblock %}

virvo/templates/virvo/table_station.html
{% load render_table from django_tables2 %}


{% render_table table %}