dma/urls.py
from django.conf.urls import url

from django.views.generic import TemplateView

from .views import (
    DmazoneListview,
    
    WbalanceListview,
    EconomyListview,
    StaticListview,
    press_value,
    MeasureCreateView,
    MeasureUpdateView,
)

app_name = 'dma'
urlpatterns = [
    #url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', DmazoneListview.as_view(), name='detail'),
    url(r'^$', DmazoneListview.as_view()),
    # url(r'^(?P<slug>[\w-]+)/wbalance/$', TemplateView.as_view(template_name='dma/wbalance.html'),name='wbalance'),
    url(r'^(?P<slug>[\w-]+)/wbalance/$', WbalanceListview.as_view()),
    url(r'^(?P<slug>[\w-]+)/economy/$', EconomyListview.as_view()),
    url(r'^(?P<slug>[\w-]+)/static/$', StaticListview.as_view()),

    #dma create update etc
    url(r'^(?P<slug>[\w-]+)/create/$', MeasureCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$', MeasureUpdateView.as_view(), name='edit'),

    url(r'^press_value', press_value, name='press_value'),
    
]

water/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

from . import views

app_name = 'water'
urlpatterns = [
    
    url(r'^$', views.WaterListview.as_view(),name='home'),

    #数据监控
    url(r'station_monitor/',views.StaionMonitorView.as_view(),name='station_monitor'),
    url(r'dma_online/',views.DmaOnlineView.as_view(),name='dma_online'),
    url(r'rt_curve/',views.RTCurveView.as_view(),name='rt_curve'),
    url(r'big_user_online/',views.BigUserOnlineView.as_view(),name='big_user_online'),

    #数据分析 
    url(r'analy_usage/',views.AnalyUsageView.as_view(),name='analy_usage'),
    url(r'analy_flow_press/',views.AnalyFlowPressView.as_view(),name='analy_flow_press'),
    url(r'ajax/load_station',views.ajax_load_station,name='ajax_load_station'),

    #设备管理 
    url(r'flowmeter/',views.FlowMeterView.as_view(),name='flow_meter'),
]

water/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.dateparse import parse_datetime
from django.contrib.admin import widgets
from django.contrib.admin.widgets import AdminDateWidget,AdminSplitDateTime
from django.contrib.postgres.forms.ranges import DateRangeField, RangeWidget


from . import models
import datetime


class SearchForm(forms.Form):
    name = forms.CharField(max_length=120,initial='shenzhen')


class AnalyWaterForm(forms.Form):
    organization = forms.ChoiceField()
    station      = forms.ModelChoiceField(queryset=models.Tblfminfo.objects.all(),to_field_name='simid')
    readdate     = forms.ChoiceField()
    date         = forms.DateField(widget=AdminDateWidget())

    def __init__(self, *args, **kwargs):
        super(AnalyWaterForm, self).__init__(*args, **kwargs)

        organs = models.Tblfminfo.objects.all().distinct('filialename')
        fns = [f.filialename for f in organs]
        self.fields['organization'].choices = tuple(enumerate(fns))

        press_all = models.PressShareDayTax.objects.all().distinct('simid')

        pr_rtime = [x.readtime[:10] for x in press_all]
        self.fields['readdate'].choices = tuple(enumerate(pr_rtime))

        self.fields['organization'].initial = fns[1]
        self.fields['station'].initial = models.Tblfminfo.objects.first()
        self.fields['readdate'].initial = pr_rtime[0][:10]
        self.fields['date'].initial = pr_rtime[0][:10]

        # flows_all = models.FlowShareDayTax.objects.all().distinct('simid')

class DateRangeForm(forms.Form):
    date_range = DateRangeField(widget=RangeWidget(AdminDateWidget()))


class WatermeterForm(forms.ModelForm):
    the_id = forms.IntegerField(widget=forms.HiddenInput)
    # rtime = forms.DateField(widget=AdminSplitDateTime())
    # lastrtime = forms.DateField(widget=AdminSplitDateTime())
    
    class Meta:
        fields = ('nodeaddr','wateraddr','rvalue','fvalue','metertype','meterstate','commstate','rtime','lastrvalue','lastrtime','dosage','islargecalibermeter')
        model = models.Watermeter
        widgets = {
            'rtime':widgets.AdminSplitDateTime(),
            'lastrtime':widgets.AdminSplitDateTime()
        }

    def __init__(self, *args, **kwargs):
        super(WatermeterForm, self).__init__(*args, **kwargs)

        instance = getattr(self, 'instance', None)
        if instance and instance.id:
            self.fields["the_id"].initial = instance.id

            # print self.instance.rtime,type(self.instance.rtime),instance.lastrtime
            # if isinstance(instance.rtime,unicode):
            #     self.fields['rtime'].initial = parse_datetime(instance.rtime)
            #     self.fields['lastrtime'].initial = parse_datetime(instance.lastrtime)

            #     print self.instance.rtime,type(self.instance.rtime),instance.rtime
        # self.initial['rtime'] = parse_datetime(self.instance.rtime)
        # self.instance.rtime = parse_datetime(self.instance.rtime)

        # print self.instance.rtime,type(self.instance.rtime)

    def clean(self):
        
        self.cleaned_data['communityid'] = self.cleaned_data['community'].id
        

    def save_existing(self, form, instance, commit=True):
        """Save and return an existing model instance for the given form."""
        
        return form.save(commit=commit)

    def save(self,commit=True):
        
        instance = super(WatermeterForm, self).save(commit)
        

water/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,HttpResponse
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView,FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from dma.fusioncharts import FusionCharts
from .forms import SearchForm,AnalyWaterForm,DateRangeForm
from .models import FlowShareDayTax,PressShareDayTax,Tblfminfo
import django_tables2 as tables
from django_tables2 import RequestConfig
from django.db import connection
from django.utils.html import format_html
from django.utils.safestring import mark_safe

import random

import logging

log = logging.getLogger("error_logger")

def nightflow(chartid,chartname,width=600,height=400):
    # Create an object for the column2d chart using the FusionCharts class constructor
    flow_list=[random.randint(1,5) for _ in range(20)]
    
    cates = [{"label":n} for n in range(20) ]
    values0 = [{"value":10} for v in flow_list ]
    values = [{"value":v} for v in flow_list ]
    datasource = {}
    datasource["chart"] = {
        "caption": "夜间最小流量",
        "subcaption": 'day',
        "xaxisname": "Time",
        "yaxisname": "watermeter flow",
        "numberprefix": "$",
        "theme": "ocean"
    }
    datasource["categories"] = [{
        "category": cates
    }]

    datasource["dataset"] = [ {
            "seriesname": "flow ceiling",
            "renderas": "line",
            "showvalues": "0",
            "data": values0
        }, {
            "seriesname": "meter flow",
            "renderas": "line",
            "showvalues": "0",
            "data": values
        }
    ]
    column2d = FusionCharts("mscombi2d", chartid , width, height, chartname, "json",datasource)

    return column2d

# Create your views here.
def dma_online(request):
    return render(request,"water/dma_online.html",{'output':nightflow().render()})



class WaterListview(ListView):

    template_name = 'water/water_home.html'

    def get_queryset(self):
        return None

    def get_context_data(self, *args, **kwargs):
        
        context = super(WaterListview, self).get_context_data(*args, **kwargs)
        
        return context


class StaionMonitorView(TemplateView):
    template_name = 'water/station_monitor.html'

    def get_context_data(self, *args, **kwargs):
        
        context = super(StaionMonitorView, self).get_context_data(*args, **kwargs)

        
        
        return context

class DmaOnlineView(TemplateView):
    template_name = 'water/dma_online.html'

    def get_context_data(self, *args, **kwargs):
        
        context = super(DmaOnlineView, self).get_context_data(*args, **kwargs)

        context['output'] = nightflow("ext1","chart-1").render()
        
        return context


class RTCurveView(TemplateView):
    template_name = 'water/rt_curve.html'

    def get_context_data(self, *args, **kwargs):
        
        context = super(RTCurveView, self).get_context_data(*args, **kwargs)

        context['output'] = nightflow("ext2","chart-1").render()
        context['output2'] = nightflow("ext3","chart-2").render()
        context['output3'] = nightflow("ext4","chart-3").render()
        context['output4'] = nightflow("ext5","chart-4").render()
        
        return context                



class BigUserOnlineView(TemplateView):
    
    template_name = 'water/big_user_online.html'

    def get_context_data(self, *args, **kwargs):
        
        context = super(BigUserOnlineView, self).get_context_data(*args, **kwargs)

        form = SearchForm(self.request.POST or None)
        context['form'] = form

        # context['big_user'] = form.cleaned_data['name'] 
        
        return context       

    def post(self,request,*args,**kwargs) :
        context = self.get_context_data()

        if context['form'].is_valid():
            pass
            
        

        return super(BigUserOnlineView,self).render_to_response(context)



#数据分析
class AnalyUsageView(TemplateView):
    template_name = 'water/analy_usage.html'        


    def get_context_data(self, *args, **kwargs):
        
        context = super(AnalyUsageView, self).get_context_data(*args, **kwargs)

        form = AnalyWaterForm(self.request.POST or None)
        context['form'] = form

        context['output'] = nightflow("ext1","chart-day_water",1100,600).render()

        range_form = DateRangeForm(self.request.POST or None)
        context['range_form'] = range_form

        contact_list = range(100)

        paginator = Paginator(contact_list, 10) # Show 25 contacts per page

        page = self.request.GET.get('page')
        try:
            contacts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            contacts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            contacts = paginator.page(paginator.num_pages)
        context['contacts'] = contacts
                
        return context      

    def post(self,request,*args,**kwargs):
        context = self.get_context_data()

        if context['form'].is_valid():

            if "today" in self.request.POST:
                pass

            elif "prevday" in self.request.POST:
                pass
            
            else:
                pass

        elif context['range_form'].is_valid():
            pass

        else:
            pass
        

        return super(AnalyUsageView,self).render_to_response(context)


def ajax_load_station(request):
    organization = request.GET.get('organization')
    # print 'organization',organization

    stations = Tblfminfo.objects.filter(filialename__icontains=organization)
    return render(request,'water/stations_list.html',{'stations':stations})

class AnalyFlowPressView(TemplateView):
    template_name = 'water/analy_flow_press.html'        


    def draw_chart(self,chartid,chartname,width,height,flow_list):
        # Create an object for the column2d chart using the FusionCharts class constructor
        flow_list=flow_list
        
        if len(flow_list)>0:
            subc = flow_list[0].readtime[:10]
        else:
            subc = "day"

        cates = [{"label":v.readtime[11:]} for v in flow_list ]
        values0 = [{"value":10} for v in flow_list ]
        values = [{"value":v.flux} for v in flow_list ]
        datasource = {}
        datasource["chart"] = {
            "caption": "夜间最小流量",
            "subcaption": subc,
            "xaxisname": "Time",
            "yaxisname": "watermeter flow",
            "numberprefix": "$",
            "theme": "ocean"
        }
        datasource["categories"] = [{
            "category": cates
        }]

        datasource["dataset"] = [ {
                "seriesname": "flow ceiling",
                "renderas": "line",
                "showvalues": "0",
                "data": values0
            }, {
                "seriesname": "meter flow",
                "renderas": "line",
                "showvalues": "0",
                "data": values
            }
        ]
        column2d = FusionCharts("mscombi2d", chartid , width, height, chartname, "json",datasource)

        return column2d

    def get_context_data(self, *args, **kwargs):
        
        context = super(AnalyFlowPressView, self).get_context_data(*args, **kwargs)

        if self.request.method == 'POST':
            form = AnalyWaterForm(self.request.POST or None)
        else:
            
            form = AnalyWaterForm()
            
        context['form'] = form

        # print form['organization'].value(), form['station'].value(),form['readdate'].value(),form['date'].value()

        context['output'] = nightflow("ext1","chart-day_water",1100,600).render()

        
                
        return context      



    def post(self,request,*args,**kwargs):
        context = self.get_context_data()

        if context['form'].is_valid():

            if "today" in self.request.POST:
                pass

            elif "prevday" in self.request.POST:
                pass
            
            else:
                ix=context['form'].cleaned_data['organization']
                
                st = context['form'].cleaned_data['station']
                simid = st.simid
                rtime = context['form'].cleaned_data['readdate']

                log.error(simid)


                
                flow_list=FlowShareDayTax.objects.filter(simid=simid).filter(readtime__icontains=rtime)
                press_list=PressShareDayTax.objects.filter(simid=simid).filter(readtime__icontains=rtime)
                
                # print len(flow_list),flow_list[0].readtime
                # for fl in flow_list:
                #     print fl.simid,fl.readtime

                if len(flow_list)>0:
                    subc = flow_list[0].readtime[:10]
                else:
                    subc = "day"
                cates = [{"label":v.readtime[11:]} for v in flow_list ]
                if len(press_list) == 0:
                    values0 = [{"value":1} for v in flow_list ]
                else:
                    values0 = [{"value":v.pressure} for v in press_list ]
                values = [{"value":v.flux} for v in flow_list ]
                datasource = {}
                datasource["chart"] = {
                    "caption": "flow day data",
                    "subcaption": subc,
                    "xaxisname": "Time",
                    "yaxisname": "watermeter flow",
                    "numberprefix": "$",
                    "theme": "ocean"
                }
                datasource["categories"] = [{
                    "category": cates
                }]

                datasource["dataset"] = [ {
                        "seriesname": "press ceiling",

water/templates/water/analy_flow_press.html

{% extends "water/water_home.html" %}

{% load static %}

{% block stylesheet %}
    {{ block.super }}
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
{{ form.media }}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>


{% endblock %}

{% block content %}
    {% block breadcrumbs %}
        <ol class="breadcrumb">
            <li><a href="{% url 'water:home' %}">Home</a></li>
            <li>数据分析</li>
            <li><a href="{% url 'water:analy_usage' %}">压力流量分析</a></li>
            
        </ol>
    {% endblock %}

    <h1>日用水量分析</h1>

    <form id="searchForm" class="form-inline" role="search" method='POST' data-station-url="{% url 'water:ajax_load_station' %}" action='.' data-url='{{ request.build_absolute_uri|safe }}'>
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            {{ form.organization.errors }}
            <label for="{{ form.organization.id_for_label }}">组织:</label>
            {{ form.organization }}
        </div>
        <div class="form-group">
            {{ form.station.errors }}
            <label for="{{ form.station.id_for_label }}">站点名称:</label>
            {{ form.station }}
        </div>
        <div class="form-group">
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">pr日期:</label>
            {{ form.readdate }}
        </div>
        <div class="form-group">
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">日期:</label>
            {{ form.date }}
        </div>
        <div class="form-group pull-right">
            <button type='submit' name="today">今天</button>
            <button type='submit' name="prevday">前一天</button>
            <button type='submit' name="query">查询</button>
        </div>
        
    </form>
    <br>

    <div class = "panel panel-primary col-md-12">
        <div class = "panel-heading">
          压力流量分析
       </div>
       <div class = "panel-body">
            <div id="chart-day_water" class="col-md-12">
                <h4 class="sub-header">压力流量分析</h4>
                {{ output|safe }}
            </div>

       </div>
   </div>

   <div class="col-md-12" style="background-color: rgba(45, 182, 224, 0.09);">
        <p>
            
            <div class="col-md-4"><h1>平均压力：0.825 MPa </h1></div>            
            <div class="col-md-4"><h1>最高压力：0.925 MPa</h1></div>         
            <div class="col-md-4"><h1>最低压力：0.683 MPa</h1></div>
            
            <div class="col-md-4"><h1>平均流量：320.28 m3/h</h1></div>         
            <div class="col-md-4"><h1>对应瞬时流量：350.56 m3/h</h1></div>     
            <div class="col-md-4"><h1>对应瞬时流量：275.01 m3/h</h1></div>

        </p>
    </div>


    



{% endblock %}    



{% block javascript %}
 super() 
<script type="text/javascript">
     $("#id_organization").change(function () {
      var url = $("#searchForm").attr("data-station-url");  // get the url of the `load_cities` view
      var idx = $(this).val();
      var myselect=document.getElementById("id_organization");
      var organization =  myselect.options[idx].text; // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'organization': organization       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_station").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });


</script>
{% endblock %}

water/templates/water/analy_usage.html

{% extends "water/water_home.html" %}

{% load static %}

{% block stylesheet %}
    {{ block.super }}
<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="{% static 'admin/js/core.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'admin/js/jquery.init.js' %}"></script>
{{ form.media }}
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/base.css' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'admin/css/widgets.css' %}"/>


{% endblock %}

{% block content %}
    {% block breadcrumbs %}
        <ol class="breadcrumb">
            <li><a href="{% url 'water:home' %}">Home</a></li>
            <li>数据分析</li>
            <li><a href="{% url 'water:analy_usage' %}">日用水量分析</a></li>
            
        </ol>
    {% endblock %}

    <h1>日用水量分析</h1>

    <form id="searchForm" class="form-inline" role="search" method='POST' data-station-url="{% url 'water:ajax_load_station' %}" action='.' data-url='{{ request.build_absolute_uri|safe }}'>
        {% csrf_token %}
        {{ form.non_field_errors }}

        <div class="form-group">
            {{ form.organization.errors }}
            <label for="{{ form.organization.id_for_label }}">组织:</label>
            {{ form.organization }}
        </div>
        <div class="form-group">
            {{ form.station.errors }}
            <label for="{{ form.station.id_for_label }}">站点名称:</label>
            {{ form.station }}
        </div>
        <div class="form-group">
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">pr日期:</label>
            {{ form.readdate }}
        </div>
        <div class="form-group">
            {{ form.date.errors }}
            <label for="{{ form.date.id_for_label }}">日期:</label>
            {{ form.date }}
        </div>
        <div class="form-group pull-right">
            <button type='submit' name="today">今天</button>
            <button type='submit' name="prevday">前一天</button>
            <button type='submit' name="query">查询</button>
        </div>
        
    </form>

    <div class = "panel panel-primary col-md-12">
        <div class = "panel-heading">
          日用水量分析
       </div>
       <div class = "panel-body">
            <div id="chart-day_water" class="col-md-12">
                <h4 class="sub-header">压力流量分析</h4>
                {{ output|safe }}
            </div>

       </div>
   </div>

   <div class="col-md-12" style="background-color: rgba(45, 182, 224, 0.09);">
        <p>
            
            <div class="col-md-4"><h1>当天用水量：AAAAA.Am3</h1></div>            
            <div class="col-md-4"><h1>昨日用水量：BBBBB.Bm3</h1></div>         
            <div class="col-md-4"><h1>去年同期用水量：CCCCC.Cm3</h1></div>
            
            <div class="col-md-4"><h1>最大时段用水量：370.3m3 (9-10)</h1></div>         
            <div class="col-md-4"><h1>最小时段用水量：268.7m3 （4-5）</h1></div>     
            <div class="col-md-4"><h1>平均时段用水量：310.9m3</h1></div>

            <div class="col-md-3"><h1>当天日基准：DDDDD.Dm3</h1></div>
            <div class="col-md-3"><h1>基准差值：12.1m3</h1></div>
            <div class="col-md-3"><h1>环比增量：6.5m3</h1></div>
            <div class="col-md-3"><h1>同比增量：15m3</h1></div>
        </p>
    </div>

    <div class = "panel panel-primary col-md-12">
        <div class = "panel-heading">
          站点数据采样明细
       </div>
       <div class = "panel-body">
            <form class="form-inline" role="form" method='POST' action='.' data-url='{{ request.build_absolute_uri|safe }}'>
                {% csrf_token %}
                <div class="form-group">{{ range_form.as_p }}</div>
                
                <div class="form-group"><input type="submit" value="查询" /></div>
                
            </form>
            <table class="table table-stripped table-bordered">
                <tr>
                    <th>序号</th>
                    <th>站点名称</th>
                    <th>采样时间</th>
                    <th>采样间隔M</th>
                    <th>正向累计水量m3</th>
                    <th>反向累计水量m3</th>
                    <th>瞬时流量m3/h</th>
                    <th>压力MPa</th>
                    <th>基表电量%</th>
                    <th>远传电量%</th>
                    <th>信号强度%</th>
                </tr>
                <tr>
                    <td>1</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    
                </tr>
                <tr>
                    <td>2</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    
                </tr>

                <tr>
                    <td>3</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    
                </tr>

                <tr>
                    <td>4</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    
                </tr>
            </table>

            <form class="form-horizontal">
                            <div class="form-group">
                                <label for="items">每页</label>
                                <select id="items">
                                  <option>10</option>
                                  <option>20</option>
                                  <option>30</option>
                                  
                                </select>
                                <label >条记录</label>
                            </div>
                        </form>

              
                    {% if contacts.has_other_pages %}
                      <ul class="pagination" style="padding-left: 100px;">
                        

                        {% if contacts.has_previous %}
                          <li><a href="?page={{ contacts.previous_page_number }}">&laquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&laquo;</span></li>
                        {% endif %}
                        {% for i in contacts.paginator.page_range %}
                          {% if contacts.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                          {% else %}
                            <li><a href="?page={{ i }}">{{ i }}</a></li>
                          {% endif %}
                        {% endfor %}
                        {% if contacts.has_next %}
                          <li><a href="?page={{ contacts.next_page_number }}">&raquo;</a></li>
                        {% else %}
                          <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}


                      </ul>
                    {% endif %}
                <div id="demo_pag1" class="well">
                    <div class="row">
                        <div class="col-xs-6 col-sm-4 col-md-2 row-space">
                            <div class="input-group" style="margin-top: 20px;">
                                <span class="input-group-addon" title="Rows per page"><i class="glyphicon glyphicon-th-list"></i></span><input id="rows_per_page_demo_pag1" value="10" type="text" class="form-control small-input" title="Rows per page">
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-12 col-md-6">
                            <div class="">
                                <ul id="nav_list_demo_pag1" class="pagination pagination_custom" unselectable="on" style="user-select: none;">
                                    <li class="active"><a id="nav_item_demo_pag1_1" href="javascript:void(0);" title="Page 1 of 100">1</a></li>
                                    <li><a id="nav_item_demo_pag1_2" href="javascript:void(0);">2</a></li>
                                    <li><a id="nav_item_demo_pag1_3" href="javascript:void(0);">3</a></li>
                                    <li><a id="nav_item_demo_pag1_4" href="javascript:void(0);">4</a></li>
                                    <li><a id="nav_item_demo_pag1_5" href="javascript:void(0);">5</a></li>
                                    <li><a id="next_demo_pag1" href="javascript:void(0);">→</a></li>
                                    <li><a id="last_demo_pag1" href="javascript:void(0);">»</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-4 col-md-2">
                            <div class="input-group" style="margin-top: 20px;">
                                <span class="input-group-addon" title="Go to page"><i class="glyphicon glyphicon-arrow-right"></i></span><input id="goto_page_demo_pag1" type="text" class="form-control small-input" title="Go to page">
                            </div>
                        </div>
                        
                        <div class="col-xs-12 col-sm-4 col-md-2 row-space">
                            <div id="rows_info_demo_pag1" class="" style="margin-top: 20px;">
                                1-10 of 1000 records (p.1/100)

                            </div>
                        </div>
                    </div>
                </div>

        </div>
    
   </div>

    

    



{% endblock %}    

water/templates/water/stations_list.html
<option value="">---------</option>
{% for station in stations %}
<option value="{{ station.simid }}">{{ station.username }}</option>
{% endfor %}