dma/urls.py
from django.conf.urls import url

from django.views.generic import TemplateView

from .views import (
    DmazoneListview,
    
    WbalanceListview,
    EconomyListview,
    StaticListview,
    press_value,
    MeasureCreateView,
    MeasureUpdateView,
)

app_name = 'dma'
urlpatterns = [
    #url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', DmazoneListview.as_view(), name='detail'),
    url(r'^$', DmazoneListview.as_view()),
    # url(r'^(?P<slug>[\w-]+)/wbalance/$', TemplateView.as_view(template_name='dma/wbalance.html'),name='wbalance'),
    url(r'^(?P<slug>[\w-]+)/wbalance/$', WbalanceListview.as_view()),
    url(r'^(?P<slug>[\w-]+)/economy/$', EconomyListview.as_view()),
    url(r'^(?P<slug>[\w-]+)/static/$', StaticListview.as_view()),

    #dma create update etc
    url(r'^(?P<slug>[\w-]+)/create/$', MeasureCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/edit/$', MeasureUpdateView.as_view(), name='edit'),

    url(r'^press_value', press_value, name='press_value'),
    
]

gis/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import TemplateView

from . import cookbook as cb

app_name = 'gis'
urlpatterns = [
    url(r'^$',views.index,name='index'),

    url(r'^(?P<page>.+\.html)$', views.StaticView.as_view()),
    url(r'^(?P<page>.+\.gml)$', views.StaticView.as_view()),
    url(r'^(?P<page>.+\.kml)$', views.StaticView.as_view()),
    url(r'^(?P<page>.+\.png)$', views.StaticView.as_view()),
    url(r'^(?P<page>.+\.json)$', views.StaticView.as_view()),
    url(r'^(?P<page>.+\.geojson)$', views.StaticView.as_view()),

    url(r'^getGeom',views.getGeom,name='getGeom'),
    url(r'^getFeatureEx',views.getFeatureEx,name='getFeatureEx'),
    url(r'^getgeojson',views.getgeojson,name='getgeojson'),
    url(r'^getTopoByNode',views.getTopoByNode,name='getTopoByNode'),
    url(r'^country/', TemplateView.as_view(template_name='gis/country.html')),
    url(r'^data/geojson/countries.geojson',views.countries,name='countries'),
    # url(r'^data/geojson/countries.geojson',TemplateView.as_view(template_name='data/geojson/countries.geojson')),

    url(r'^cookbook/$', TemplateView.as_view(template_name='gis/cookb/cookbook.html')),
    # url(r'^cookbook/ch01',cb.ch01,name='fullscreen'),
    url(r'^cookbook/ch01-map-controls/$',cb.ch01_map_controls,name='map_control'),
    url(r'^cookbook/ch01-moving-around/$',cb.ch01_moving_around,name='moving_around'),
    url(r'^cookbook/ch01-map-extent/$',TemplateView.as_view(template_name='gis/cookb/ch01_map_extent.html'),name='map_extent'),

    url(r'^cookbook/ch02-bing-maps/$',TemplateView.as_view(template_name='gis/cookb/ch02_bing_maps.html'),name='bing_maps'),
    url(r'^cookbook/ch02-openstreetmap/$',TemplateView.as_view(template_name='gis/cookb/ch02_openstreetmap.html'),name='openstreetmap'),
    url(r'^cookbook/ch02-wms-layers/$',TemplateView.as_view(template_name='gis/cookb/ch02_wms_layers.html'),name='wms_layers'),
    url(r'^cookbook/ch02-zoom-effect/$',TemplateView.as_view(template_name='gis/cookb/ch02_zoom_effect.html'),name='zoom_effect'),
    url(r'^cookbook/ch02-layer-opacity/$',TemplateView.as_view(template_name='gis/cookb/ch02_layer_opcity.html'),name='layer_opacity'),
    url(r'^cookbook/ch02-layer-preloading/$',TemplateView.as_view(template_name='gis/cookb/ch02_layer_preloading.html'),name='layer_preloading'),
    url(r'^cookbook/ch02-image-layer/$',TemplateView.as_view(template_name='gis/cookb/ch02_image_layer.html'),name='image_layer'),
    url(r'^cookbook/ch02-tile-size/$',TemplateView.as_view(template_name='gis/cookb/ch02_tile_size.html'),name='tile_size'),


    url(r'^cookbook/ch03-gml-layer/$',TemplateView.as_view(template_name='gis/cookb/ch03_gml_layer.html'),name='gml_layer'),
    url(r'^cookbook/ch03-kml-layer/$',TemplateView.as_view(template_name='gis/cookb/ch03_kml_layer.html'),name='kml_layer'),
    url(r'^cookbook/ch03-creating-features/$',TemplateView.as_view(template_name='gis/cookb/ch03_creating_features.html'),name='creating_features'),
    url(r'^cookbook/ch03-export-geojson/$',TemplateView.as_view(template_name='gis/cookb/ch03_export_geojson.html'),name='export_geojson'),
    url(r'^cookbook/ch03-wkt-format/$',TemplateView.as_view(template_name='gis/cookb/ch03_wkt_format.html'),name='wkt_format'),
    url(r'^cookbook/ch03-markers/$',TemplateView.as_view(template_name='gis/cookb/ch03_markers.html'),name='markers'),
    url(r'^cookbook/ch03-removing-cloning-feature-overlays/$',TemplateView.as_view(template_name='gis/cookb/ch03_rcf_overlay.html'),name='rcf_overlay'),

    url(r'^cookbook/ch05-drawing-features/$',TemplateView.as_view(template_name='gis/cookb/ch05_drawing_features.html'),name='drawing_features'),
    url(r'^cookbook/ch05-modifying-features/$',TemplateView.as_view(template_name='gis/cookb/ch05_modifying_features.html'),name='modifying_features'),
    url(r'^cookbook/ch05-measuring/$',TemplateView.as_view(template_name='gis/cookb/ch05_measuring.html'),name='measuring'),
    url(r'^cookbook/ch05-add-remove-controls/$',TemplateView.as_view(template_name='gis/cookb/ch05_add_remove_features.html'),name='add_remove_control'),
    url(r'^cookbook/ch05-geolocation/$',TemplateView.as_view(template_name='gis/cookb/ch05_geolocation.html'),name='geolocation'),
    url(r'^cookbook/ch05-wms-feature-info/$',TemplateView.as_view(template_name='gis/cookb/ch05_wms_feature_info.html'),name='wms_feature_info'),
    url(r'^cookbook/ch05-feature-info-from-source/$',TemplateView.as_view(template_name='gis/cookb/ch05_feature_info_from_source.html'),name='feature_info_from_source'),


    url(r'^cookbook/map-layer', TemplateView.as_view(template_name='gis/cookb/map-layers.html')),
]

gis/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponse,JsonResponse
from django.contrib import messages
from django.contrib.gis.geos import Polygon
from django.views.generic import TemplateView
from django.template import TemplateDoesNotExist
from django.http import Http404

import json
from gis import models as gis_model
import os
#from models import *
# Create your views here.

scada_classes_all = dict([(name, cls) for name, cls in gis_model.__dict__.items() if isinstance(cls, type)])


class StaticView(TemplateView):
    def get(self, request, page, *args, **kwargs):
        self.template_name = page
        print(page)
        response = super(StaticView, self).get(request, *args, **kwargs)
        try:
            return response.render()
        except TemplateDoesNotExist:
            raise Http404()


def return_feature_collection(cur):
    """
    Execute a JSON-returning SQL and return HTTP response
    :type sql: SQL statement that returns a a GeoJSON Feature
    """
    

    def generate():
        yield '{ "type": "FeatureCollection", "features": ['
        for idx, row in enumerate(cur):
            
            if idx > 0:
                yield ','
            yield '{ "type":"Feature","geometry":'
            yield row 
            yield '}'
        yield ']}'
        
    return HttpResponse(generate())

def get_table_by_name(tablename):
    cls = None
    rets = "no such gist table %s "% tablename
    for k,v in scada_classes_all.items():
        try:
            if v._meta.db_table == tablename:
                cls = v
        except:
            continue
    
    return cls
    

def index(request):
    
    return render(request,'gis/index.html')

def getgeojson(request):
    pgeojson = {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[-11862500.221591014,3921338.452036796],[-11846533.373609068,3910467.407495644],[-11853837.35527513,3885667.837281932],[-11881694.40662025,3889404.76073825],[-11896744.01026277,3907953.478824563],[-11877040.243489852,3921712.145082231],[-11862500.221591014,3921338.452036796]]]},"properties":"null"}]}

    # pgeojson = '{\"type\":\"FeatureCollection\",\"features\":[{\"type\":\"Feature\",\"geometry\":{\"type\":\"Polygon\",\"coordinates\":[[[-11888590.72569057,3901328.9348180657],[-11861922.698414044,3926128.506198114],[-11832876.627665678,3917635.5016297945],[-11841709.349897442,3881285.449215365],[-11863111.717817292,3881795.0262937024],[-11884344.225155914,3889948.3108659033],[-11888590.72569057,3901328.9348180657]]]},\"properties\":null}]}'
    pgeojson = {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Polygon","coordinates":[[[13178892.355395831,3489944.851357296],[13181281.012238158,3490454.4314972665],[13181822.4413829,3488777.063506157],[13180803.280811375,3487460.647792236],[13178648.181393484,3487938.3792190184],[13178202.298825681,3489021.2372169197],[13178892.355395831,3489944.851357296]]]},"properties":"null"}]}
    
    pgeojson = {"type": "FeatureCollection", "features": [{"type": "Feature", "geometry": {"type": "Polygon", "coordinates": [[[13178314.864293117, 3490254.912364093], [13179270.327146681, 3490562.783792816], [13179397.721999435, 3489989.5060806773], [13179111.083143365, 3489777.1809373107], [13178569.653998623, 3489639.169506647], [13178612.11914393, 3490010.7383617465], [13178357.329438424, 3489968.2735080235], [13178527.189436484, 3490191.2149377167], [13178314.864293117, 3490254.912364093]]]}, "properties": {"name": "fuck"}}]}
    return JsonResponse(pgeojson)
    
def getFeatureEx(request):
    # return getGeom(request)

    nodes = '''{
        "features":[
        {
            "geometry":{
                "coordinates":[
                    118.39236,
                    29.88531
                ],
                "type":"Point"
            },
            "properties":{
                "angle":0,
                "caliber":0,
                "className":"ws_flow_meter",
                "endAltitude":0,
                "endDepth":0,
                "id":"00000011000000200",
                "industryCode":"JSKZ00020",
                "length":0,
                "lineWidth":0,
                "startAltitude":0,
                "startDepth":0
            },
            "type":"Feature"
        },
        {
            "geometry":{
                "coordinates":[
                    118.39530,
                    29.88569
                ],
                "type":"Point"
            },
            "properties":{
                "angle":0,
                "caliber":0,
                "className":"ws_flow_meter",
                "endAltitude":0,
                "endDepth":0,
                "id":"00000011000000200",
                "industryCode":"JSKZ00021",
                "length":0,
                "lineWidth":0,
                "startAltitude":0,
                "startDepth":0
            },
            "type":"Feature"
        },
        {
            "geometry":{
                "coordinates":[
                    118.39767484,
                    29.882346264
                ],
                "type":"Point"
            },
            "properties":{
                "angle":0,
                "caliber":0,
                "className":"ws_flow_meter",
                "endAltitude":0,
                "endDepth":0,
                "id":"00000011000000200",
                "industryCode":"JSKZ00020",
                "length":0,
                "lineWidth":0,
                "startAltitude":0,
                "startDepth":0
            },
            "type":"Feature"
        },
        {
            "geometry":{
                "coordinates":[
                    118.39977133,
                    29.883191412
                ],
                "type":"Point"
            },
            "properties":{
                "angle":0,
                "caliber":0,
                "className":"ws_flow_meter",
                "endAltitude":0,
                "endDepth":0,
                "id":"00000011000000200",
                "industryCode":"JSKZ00021",
                "length":0,
                "lineWidth":0,
                "startAltitude":0,
                "startDepth":0
            },
            "type":"Feature"
        },
            {
                "geometry":{
                    "coordinates":[
                        [
                            118.39237074,
                            29.885314617
                        ],
                        [
                            118.39534361,
                            29.885658422
                        ]
                    ],
                    "type":"LineString"
                },
                "properties":{
                    "angle":0,
                    "caliber":0,
                    "className":"ws_pipe",
                    "endAltitude":0,
                    "endDepth":0,
                    "id":"00000001000076520",
                    "length":0,
                    "lineWidth":0,
                    "startAltitude":0,
                    "startDepth":0
                },
                "type":"Feature"
            },
            {
                "geometry":{
                    "coordinates":[
                        [
                            118.39116966,
                            29.887703719
                        ],
                        [
                            118.39237074,
                            29.885314617
                        ]
                    ],
                    "type":"LineString"
                },
                "properties":{
                    "angle":0,
                    "caliber":0,
                    "className":"ws_pipe",
                    "endAltitude":0,
                    "endDepth":0,
                    "id":"00000001000076510",
                    "length":0,
                    "lineWidth":0,
                    "startAltitude":0,
                    "startDepth":0
                },
                "type":"Feature"
            },
            {
                "geometry":{
                    "coordinates":[
                        [
                            118.39767484,
                            29.882346264
                        ],
                        [
                            118.39977133,
                            29.883191412
                        ]
                    ],
                    "type":"LineString"
                },
                "properties":{
                    "angle":0,
                    "caliber":0,
                    "className":"ws_pipe",
                    "endAltitude":0,
                    "endDepth":0,
                    "id":"00000001000076550",
                    "length":0,
                    "lineWidth":0,
                    "startAltitude":0,
                    "startDepth":0
                },
                "type":"Feature"
            },
            {
                "geometry":{
                    "coordinates":[
                        [
                            118.39534361,
                            29.885658422
                        ],
                        [
                            118.39638227,
                            29.884213138
                        ]
                    ],
                    "type":"LineString"
                },
                "properties":{
                    "angle":0,
                    "caliber":0,
                    "className":"ws_pipe",
                    "endAltitude":0,
                    "endDepth":0,
                    "id":"00000001000076530",
                    "length":0,
                    "lineWidth":0,
                    "startAltitude":0,
                    "startDepth":0
                },
                "type":"Feature"
            },
            {

gis/templates/gis/cookb/ch01_map_extent.html
{% extends 'gis/cookb/cookbook.html' %}

{% block title %}Openlayer3 cookbook|ch01 map control {% endblock %}


{% block stylesheet %}
<style type="text/css">

.map {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
}


</style>
{% endblock %}

{% block content %}
    <h1>show map extents</h1>
    <div id="js-map" class="map"></div>
    

{% endblock %}


{% block javascript %}
<script type="text/javascript">

    var extent = ol.proj.transformExtent(
        [-125.0011,24.9493,-66.9326,49.5904],
        'EPSG:4326','EPSG:3857'
    );

    new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.Stamen({
                    layer: 'watercolor'
                })
            }),
            new ol.layer.Tile({
                source: new ol.source.Stamen({
                    layer: 'terrain-labels'
                }),
                extent:extent
            })
        ],
        view: new ol.View({
            center: [-12100000, 3400000],
            zoom: 6,
            minZoom:5,
            extent:extent
        }),
        target: 'js-map',
        
    });

    
</script>
{% endblock %}

gis/templates/gis/cookb/ch01_moving_around.html
{% extends 'gis/cookb/cookbook.html' %}

{% block title %}Openlayer3 cookbook|ch01 Moving around the map {% endblock %}


{% block stylesheet %}
<style type="text/css">

.map {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 20%;
    font-family: Arial, sans-serif;
}

.pane {
    position: absolute;
    top: 0;
    bottom: 0;
    right: 0;
    width: 20%;
    background: ghostwhite;
    border-left: 5px solid lightsteelblue;
    box-sizing: border-box;
    padding: 0 20px;
    font-family: Arial, sans-serif;
}

label {
    font-size: 12px;
    font-weight: bold;
    display: block;
}

p {
    margin-bottom: 5px;
}

input {
    padding: 5px;
}

</style>
{% endblock %}

{% block content %}
    <h1>show map control</h1>
    <div id="js-map" class="map"></div>
    <div class="pane">
        <h1>Navigation</h1>
        <label>
            <p>Pan to a city</p>
            <select id="js-city">
                <option value="12.5,41.9">Rome (Italy)</option>
                <option value="30.517,50.45">Kiev (Ukraine)</option>
                <option value="-9.183,38.7">Lisbon (Portugal)</option>
                <option value="-0.117,51.5">London (England)</option>
                <option value="14.417,50.083">Prague (Czech Rep)</option>
            </select>
        </label>

        <label>
            <p>Zoom</p>
            <input type="number" id="js-zoom">
        </label>

        <label>
            <p>Rotation</p>
            <input type="number" id="js-rotate">
        </label>

        <label>
            <p>Lon</p>
            <input type="number" id="js-lon">
        </label>

        <label>
            <p>Lat</p>
            <input type="number" id="js-lat">
        </label>
    </div>
    
{% endblock %}


{% block javascript %}
<script type="text/javascript">
    var map = new ol.Map({
        layers: [
            new ol.layer.Tile({
                source: new ol.source.Stamen({
                    layer: 'watercolor'
                })
            })
        ],
        view: new ol.View({
            center: ol.proj.fromLonLat([12.5, 41.9]),
            zoom: 3
        }),
        target: 'js-map',
        
    });

    var citySelect = document.getElementById('js-city');
    var zoomInput = document.getElementById('js-zoom');
    var rotateInput = document.getElementById('js-rotate');
    var lonInput = document.getElementById('js-lon');
    var latInput = document.getElementById('js-lat');

    var updateUI = function(event) {
        var view = event && event.currentTarget || map.getView();
        zoomInput.value = view.getZoom();
        rotateInput.value = view.getRotation();

        var centerLonLat = ol.proj.toLonLat(view.getCenter());
        lonInput.value = centerLonLat[0].toFixed(3);
        latInput.value = centerLonLat[1].toFixed(3);
    };
    updateUI();

    map.getView().on([
        'change:center',
        'change:resolution',
        'change:rotation'
        ],updateUI);

    var setCenter = function(lon,lat) {
        map.getView().setCenter(ol.proj.fromLonLat([
            parseFloat(lon),parseFloat(lat)
            ]));
    };

    window.addEventListener('keyup',function(event) {
        switch(event.target.id){
            case 'js-zoom':
                map.beforeRender(ol.animation.zoom({
                    resolution:map.getView().getResolution(),
                    duration:150
                }));
                map.getView().setZoom(parseInt(event.target.value,10));
                break;

            case 'js-rotate':
                map.beforeRender(ol.animation.rotate({
                    rotation:map.getView().getRotation(),
                    duration:250
                }));
                map.getView().setRotation(parseFloat(event.target.value));
                break;

            case 'js-lon':
                setCenter(event.target.value,latInput.value);
                break;

            case 'js-lat':
                setCenter(lonInput.value,event.target.value);
                break;
        }
    });

    citySelect.addEventListener('change',function() {
        map.beforeRender(ol.animation.pan({
            source:map.getView().getCenter(),
            duration:500
        }));
        setCenter.apply(null,this.value.split(','));
    });


    

</script>
{% endblock %}

gis/templates/gis/cookb/cookbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}OpenLayers 3.x Cookbook - Peter J Langley{% endblock %}</title>
    
    
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'gis/assets/css/bootstrap.min.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'gis/assets/css/index.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'gis/assets/css/ol.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'gis/assets/css/jquery-ui.css' %}" type = "text/css"/>
    

    <script src="{%  static 'gis/assets/js/ol-debug.js' %} "></script>
    <script src="{%  static 'gis/assets/js/jquery.js' %} "></script>
    <script src="{%  static 'gis/assets/js/jquery-ui.js' %} "></script>

    {% block stylesheet %}{% endblock %}
</head>
<body>

{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>OpenLayers 3.x Cookbook</h1>
        <p>Peter J Langley</p>
    </div>

    <div class="row">
        <div class="col-sm-6">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 1</h2>

                    <ol>
                        <li><a href="/gis/cookbook/ch01">Creating a simple fullscreen map</a></li>
                        <li><a href="/gis/cookbook/ch01-map-options">Playing with the map's options</a></li>
                        <li><a href="/gis/cookbook/ch01-map-layers">Managing the map's stack layers</a></li>
                        <li><a href="{% url 'gis:map_control' %}">Managing the map's controls</a></li>
                        <li><a href="{% url 'gis:moving_around' %}">Moving around map view</a></li>
                        <li><a href="{% url 'gis:map_extent' %}">Restricting the map's extent</a></li>
                    </ol>
                </li>
            </ul>
        </div>

        <div class="col-sm-6">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 2</h2>

                    <ol>
                        <li><a href="{% url 'gis:bing_maps' %}">Using Bing imagery</a></li>
                        <li><a href="{% url 'gis:openstreetmap' %}">Using OpenStreetMap imagery</a></li>
                        <li><a href="{% url 'gis:wms_layers' %}">Adding WMS layers</a></li>
                        <li><a href="{% url 'gis:zoom_effect' %}">Changing the zoom effect</a></li>
                        <li><a href="{% url 'gis:layer_opacity' %}">Changing layer opacity</a></li>
                        <li><a href="{% url 'gis:layer_preloading' %}">Buffering the layer data to improve map navigation</a></li>
                        <li><a href="{% url 'gis:image_layer' %}">Creating an image layer</a></li>
                        <li><a href="{% url 'gis:tile_size' %}">Setting the tile size in WMS layers</a></li>
                    </ol>
                </li>
            </ul>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-sm-6">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 3</h2>

                    <ol>
                        <li><a href="{% url 'gis:gml_layer' %}">Adding a GML layer</a></li>
                        <li><a href="{% url 'gis:kml_layer' %}">Adding a KML layer</a></li>
                        <li><a href="{% url 'gis:creating_features' %}">Creating features programmatically</a></li>
                        <li><a href="{% url 'gis:export_geojson' %}">Exporting features as GeoJSON</a></li>
                        <li><a href="{% url 'gis:wkt_format' %}">Reading and creating features from a WKT</a></li>
                        <li><a href="{% url 'gis:markers' %}">Using point features as markers</a></li>
                        <li><a href="{% url 'gis:rcf_overlay' %}">Removing or cloning features using overlays</a></li>
                        <li><a href="/ch03/ch03-zoom-to-extent">Zooming to the extent of a layer</a></li>
                        <li><a href="/ch03/ch03-geometry-labels">Adding text labels to geometry points</a></li>
                        <li><a href="/ch03/ch03-wfs-layer">Adding features from a WFS server</a></li>
                        <li><a href="/ch03/ch03-clustering">Using the cluster strategy</a></li>
                        <li><a href="/ch03/ch03-reading-features-from-ajax">Reading features directly using AJAX</a></li>
                        <li><a href="/ch03/ch03-heat-map">Creating a heat map</a></li>
                    </ol>
                </li>
            </ul>
        </div>

        <div class="col-sm-6">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 4</h2>

                    <ol>
                        <li><a href="/ch04/ch04-map-comparator">Creating a side-by-side map comparator</a></li>
                        <li><a href="/ch04/ch04-map-loading-progress">Implementing a work-in-progress indicator for map layers</a></li>
                        <li><a href="/ch04/ch04-vector-feature-events">Listening for the vector layer features' events</a></li>
                        <li><a href="/ch04/ch04-mouse-touch-events">Listening for mouse or touch events</a></li>
                        <li><a href="/ch04/ch04-keyboard-pan-zoom">Using the keyboard to pan or zoom</a></li>
                    </ol>
                </li>
            </ul>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-sm-6">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 5</h2>

                    <ol>
                        <li><a href="{% url 'gis:add_remove_control' %}">Adding and removing controls</a></li>
                        <li><a href="{% url 'gis:geolocation' %}">Working with geolocation</a></li>
                        <li><a href="/ch05/ch05-controls-outside-map">Placing controls outside the map</a></li>
                        <li><a href="{% url 'gis:drawing_features' %}">Drawing features across multiple vector layers</a></li>
                        <li><a href="{% url 'gis:modifying_features' %}">Modifying features</a></li>
                        <li><a href="{% url 'gis:measuring' %}">Measuring distances and areas</a></li>
                        <li><a href="{% url 'gis:feature_info_from_source' %}">Getting feature information from a data source</a></li>
                        <li><a href="{% url 'gis:wms_feature_info' %}">Getting information from a WMS server</a></li>
                    </ol>
                </li>
            </ul>
        </div>

        <div class="col-sm-6">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 6</h2>

                    <ol>
                        <li><a href="/ch06/ch06-styling-layers">Styling layers</a></li>
                        <li><a href="/ch06/ch06-styling-features-by-geometry-type">Styling features based on geometry type</a></li>
                        <li><a href="/ch06/ch06-styling-features-by-attribute">Styling based on feature attributes</a></li>
                        <li><a href="/ch06/ch06-styling-interaction-render-intents">Styling interaction render intents</a></li>
                        <li><a href="/ch06/ch06-styling-clustered-features">Styling clustered features</a></li>
                    </ol>
                </li>
            </ul>
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-sm-12">
            <ul class="list-unstyled">
                <li>
                    <h2 class="h3">Chapter 7</h2>

                    <ol>
                        <li><a href="/ch07/ch07-projections">Working with projections</a></li>
                        <li><a href="/ch07/ch07-custom-control">Creating a custom control</a></li>
                        <li><a href="/ch07/ch07-dragbox-selection">Selecting features by dragging out a selection area</a></li>
                        <li><a href="/ch07/ch07-weather-forecast-imagery">Transitioning between weather forecast imagery</a></li>
                        <li><a href="/ch07/ch07-custom-openlayers-build">Using the custom OpenLayers library build</a></li>
                        <li><a href="/ch07/ch07-freehand-drawing">Drawing in freehand mode</a></li>
                        <li><a href="/ch07/ch07-modifying-layer-appearance">Modifying layer appearance</a></li>
                        <li><a href="/ch07/ch07-drag-and-drop-import">Adding features to the vector layer by dragging and dropping them</a></li>
                        <li><a href="/ch07/ch07-map-permalinks">Making use of map permalinks</a></li>
                    </ol>
                </li>
            </ul>
        </div>
    </div>

    <hr>

    <footer>
        <p><strong>Peter J Langley</strong></p>

        <ul class="list-inline">
            <li><a href="http://pjlangley.com">pjlangley.com</a></li>
            <li><a href="http://www.codechewing.com">codechewing.com</a></li>
            <li><a href="https://twitter.com/codechewing">@codechewing</a></li>
            <li><a href="https://www.linkedin.com/in/peter-j-langley-17b83a3b">LinkedIn</a></li>
        </ul>
    </footer>
</div>
{% endblock content %} <!-- end content -->


{% block javascript %}
{% endblock javascript %}
</body>
</html>